/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/y1rTZBqQtls
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Comfortaa } from 'next/font/google'

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"

export function Component_y1rTZBqQtls() {
  return (
    <main className="container mx-auto py-12 md:py-24">
      <div className="grid gap-8 md:grid-cols-[1fr_2fr]">
        <div className="space-y-6">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold">Gamification Roadmap</h2>
            <p className="text-gray-500 dark:text-gray-400">Track your progress and achievements.</p>
          </div>
          <div className="space-y-4">
            <div className="flex items-center gap-4">
              <div className="bg-gray-100 rounded-full w-12 h-12 flex items-center justify-center dark:bg-gray-800">
                <TrophyIcon className="w-6 h-6 text-yellow-500" />
              </div>
              <div>
                <div className="font-medium">Beginner Achievements</div>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  You've completed the first set of challenges.
                </p>
              </div>
              <div className="ml-auto font-medium">12/15</div>
            </div>
            <div className="flex items-center gap-4">
              <div className="bg-gray-100 rounded-full w-12 h-12 flex items-center justify-center dark:bg-gray-800">
                <MedalIcon className="w-6 h-6 text-blue-500" />
              </div>
              <div>
                <div className="font-medium">Intermediate Achievements</div>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  You're making great progress on the next set of challenges.
                </p>
              </div>
              <div className="ml-auto font-medium">8/20</div>
            </div>
            <div className="flex items-center gap-4">
              <div className="bg-gray-100 rounded-full w-12 h-12 flex items-center justify-center dark:bg-gray-800">
                <AwardIcon className="w-6 h-6 text-green-500" />
              </div>
              <div>
                <div className="font-medium">Advanced Achievements</div>
                <p className="text-sm text-gray-500 dark:text-gray-400">You're nearing the top of the leaderboard.</p>
              </div>
              <div className="ml-auto font-medium">3/10</div>
            </div>
          </div>
        </div>
        <div className="space-y-6">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold">Your Progress</h2>
            <p className="text-gray-500 dark:text-gray-400">See how you're doing and track your age.</p>
          </div>
          <div className="grid gap-6">
            <div className="bg-gray-100 rounded-lg p-6 dark:bg-gray-800">
              <div className="flex items-center gap-4">
                <div className="bg-gray-200 rounded-full w-16 h-16 flex items-center justify-center dark:bg-gray-700">
                  <CalendarIcon className="w-8 h-8 text-gray-500 dark:text-gray-400" />
                </div>
                <div>
                  <div className="text-2xl font-bold">35</div>
                  <p className="text-gray-500 dark:text-gray-400">Your Age</p>
                </div>
                <div className="ml-auto">
                  <Button variant="outline">
                    <RefreshCwIcon className="w-5 h-5" />
                    Refresh
                  </Button>
                </div>
              </div>
              <div className="mt-4 flex items-center gap-2">
                <div className="bg-green-500 rounded-full w-3 h-3" />
                <div className="text-sm text-gray-500 dark:text-gray-400">You're looking younger!</div>
              </div>
            </div>
            <div className="bg-gray-100 rounded-lg p-6 dark:bg-gray-800">
              <div className="flex items-center gap-4">
                <div className="bg-gray-200 rounded-full w-16 h-16 flex items-center justify-center dark:bg-gray-700">
                  <TrophyIcon className="w-8 h-8 text-gray-500 dark:text-gray-400" />
                </div>
                <div>
                  <div className="text-2xl font-bold">85%</div>
                  <p className="text-gray-500 dark:text-gray-400">Completion Progress</p>
                </div>
                <div className="ml-auto">
                  <Button variant="outline">
                    <RefreshCwIcon className="w-5 h-5" />
                    Refresh
                  </Button>
                </div>
              </div>
              <div className="mt-4">
                <Progress value={85} />
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}

function AwardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="8" r="6" />
      <path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function MedalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.21 15 2.66 7.14a2 2 0 0 1 .13-2.2L4.4 2.8A2 2 0 0 1 6 2h12a2 2 0 0 1 1.6.8l1.6 2.14a2 2 0 0 1 .14 2.2L16.79 15" />
      <path d="M11 12 5.12 2.2" />
      <path d="m13 12 5.88-9.8" />
      <path d="M8 7h8" />
      <circle cx="12" cy="17" r="5" />
      <path d="M12 18v-2h-.5" />
    </svg>
  )
}


function RefreshCwIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </svg>
  )
}


function TrophyIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
      <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
      <path d="M4 22h16" />
      <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
      <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
      <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
    </svg>
  )
}
