/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QyLtzR99Lk1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Progress } from "@/components/ui/progress"
import { Button } from "@/components/ui/button"

export function Component_QyLtzR99Lk1() {
  return (
    <main className="w-full max-w-3xl mx-auto px-4 py-8 md:px-6 md:py-12">
      <h1 className="text-3xl font-bold mb-6">Daily Quests</h1>
      <div className="grid gap-6">
        <div className="bg-white dark:bg-gray-950 rounded-lg shadow-sm p-4 flex items-center gap-4">
          <div className="bg-gray-100 dark:bg-gray-800 rounded-full p-3 flex-shrink-0">
            <PlayIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-medium mb-1">Go for a 30-minute run</h3>
            <p className="text-gray-500 dark:text-gray-400 text-sm mb-2">
              Get your heart rate up and improve your cardiovascular health.
            </p>
            <div className="flex items-center gap-2">
              <Progress className="flex-1" value={75} />
              <Button size="sm">Complete</Button>
            </div>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-950 rounded-lg shadow-sm p-4 flex items-center gap-4">
          <div className="bg-gray-100 dark:bg-gray-800 rounded-full p-3 flex-shrink-0">
            <ContactIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-medium mb-1">Discuss with AI assistant</h3>
            <p className="text-gray-500 dark:text-gray-400 text-sm mb-2">
              Chat with our AI assistant to ensure you're on the right track with your health activities.
            </p>
            <div className="flex items-center gap-2">
              <Progress className="flex-1" value={50} />
              <Button size="sm">Complete</Button>
            </div>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-950 rounded-lg shadow-sm p-4 flex items-center gap-4">
          <div className="bg-gray-100 dark:bg-gray-800 rounded-full p-3 flex-shrink-0">
            <CarrotIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-medium mb-1">Eat 2 servings of leafy greens</h3>
            <p className="text-gray-500 dark:text-gray-400 text-sm mb-2">
              Increase your intake of vitamins and minerals to support overall health.
            </p>
            <div className="flex items-center gap-2">
              <Progress className="flex-1" value={25} />
              <Button size="sm">Complete</Button>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}

function CarrotIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.27 21.7s9.87-3.5 12.73-6.36a4.5 4.5 0 0 0-6.36-6.37C5.77 11.84 2.27 21.7 2.27 21.7zM8.64 14l-2.05-2.04M15.34 15l-2.46-2.46" />
      <path d="M22 9s-1.33-2-3.5-2C16.86 7 15 9 15 9s1.33 2 3.5 2S22 9 22 9z" />
      <path d="M15 2s-2 1.33-2 3.5S15 9 15 9s2-1.84 2-3.5C17 3.33 15 2 15 2z" />
    </svg>
  )
}


function ContactIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 18a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <circle cx="12" cy="10" r="2" />
      <line x1="8" x2="8" y1="2" y2="4" />
      <line x1="16" x2="16" y1="2" y2="4" />
    </svg>
  )
}


function PlayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  )
}
