/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BbXKKC28QHj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Progress } from "@/components/ui/progress"
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"

export function Component_BbXKKC28QHj() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="space-y-4 text-center">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Healthy Living Quiz</h1>
          <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Test your knowledge on nutrition, exercise, and lifestyle choices to improve your overall health and
            wellbeing.
          </p>
        </div>
        <div className="mt-12 space-y-6">
          <div className="bg-white rounded-lg shadow-sm dark:bg-gray-950">
            <div className="p-6 sm:p-8">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-xl font-semibold">
                    What is the recommended daily intake of fruits and vegetables?
                  </h2>
                  <Progress className="w-24" value={75} />
                </div>
                <div className="grid gap-2">
                  <RadioGroup>
                    <div className="flex items-center space-x-3">
                      <RadioGroupItem id="option1" value="option1" />
                      <Label htmlFor="option1">2-3 servings</Label>
                    </div>
                    <div className="flex items-center space-x-3">
                      <RadioGroupItem id="option2" value="option2" />
                      <Label htmlFor="option2">3-5 servings</Label>
                    </div>
                    <div className="flex items-center space-x-3">
                      <RadioGroupItem id="option3" value="option3" />
                      <Label htmlFor="option3">5-7 servings</Label>
                    </div>
                    <div className="flex items-center space-x-3">
                      <RadioGroupItem id="option4" value="option4" />
                      <Label htmlFor="option4">7-9 servings</Label>
                    </div>
                  </RadioGroup>
                  <Button className="w-full" size="sm" variant="outline">
                    Submit
                  </Button>
                </div>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-sm dark:bg-gray-950">
            <div className="p-6 sm:p-8">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-xl font-semibold">
                    What is the recommended amount of physical activity per week?
                  </h2>
                  <Progress className="w-24" value={50} />
                </div>
                <div className="grid gap-2">
                  <RadioGroup>
                    <div className="flex items-center space-x-3">
                      <RadioGroupItem id="option1" value="option1" />
                      <Label htmlFor="option1">30 minutes per day</Label>
                    </div>
                    <div className="flex items-center space-x-3">
                      <RadioGroupItem id="option2" value="option2" />
                      <Label htmlFor="option2">150 minutes per week</Label>
                    </div>
                    <div className="flex items-center space-x-3">
                      <RadioGroupItem id="option3" value="option3" />
                      <Label htmlFor="option3">300 minutes per week</Label>
                    </div>
                    <div className="flex items-center space-x-3">
                      <RadioGroupItem id="option4" value="option4" />
                      <Label htmlFor="option4">60 minutes per day</Label>
                    </div>
                  </RadioGroup>
                  <Button className="w-full" size="sm" variant="outline">
                    Submit
                  </Button>
                </div>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-sm dark:bg-gray-950">
            <div className="p-6 sm:p-8">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-xl font-semibold">What is the recommended amount of sleep per night?</h2>
                  <Progress className="w-24" value={25} />
                </div>
                <div className="grid gap-2">
                  <RadioGroup>
                    <div className="flex items-center space-x-3">
                      <RadioGroupItem id="option1" value="option1" />
                      <Label htmlFor="option1">6-8 hours</Label>
                    </div>
                    <div className="flex items-center space-x-3">
                      <RadioGroupItem id="option2" value="option2" />
                      <Label htmlFor="option2">7-9 hours</Label>
                    </div>
                    <div className="flex items-center space-x-3">
                      <RadioGroupItem id="option3" value="option3" />
                      <Label htmlFor="option3">8-10 hours</Label>
                    </div>
                    <div className="flex items-center space-x-3">
                      <RadioGroupItem id="option4" value="option4" />
                      <Label htmlFor="option4">9-11 hours</Label>
                    </div>
                  </RadioGroup>
                  <Button className="w-full" size="sm" variant="outline">
                    Submit
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
