/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zVFOnLQANoZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Comfortaa } from 'next/font/google'

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Component_zVFOnLQANoZ() {
  return (
    <>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                  Unlock Premium Features
                </h1>
                <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                  Elevate your health and wellness with our premium features, including an AI health assistant, new
                  pharmaceutical supplements, and expert-curated anti-aging methods.
                </p>
              </div>
            </div>
            <img
              alt="Premium Features"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
              height="550"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <div className="mx-auto grid max-w-5xl items-center gap-6 lg:grid-cols-2 lg:gap-12">
            <img
              alt="AI Health Assistant"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="310"
              src="/placeholder.svg"
              width="550"
            />
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h3 className="text-2xl font-bold">AI Health Assistant</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Get personalized health insights and recommendations from our advanced AI assistant. Track your
                  progress and receive tailored guidance to improve your overall well-being.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="mx-auto grid max-w-5xl items-center gap-6 lg:grid-cols-2 lg:gap-12">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h3 className="text-2xl font-bold">New Pharmaceutical Supplements</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Explore our exclusive line of pharmaceutical-grade supplements designed to support your health and
                  wellness goals. Backed by scientific research, these supplements can help you achieve optimal
                  performance and longevity.
                </p>
              </div>
            </div>
            <img
              alt="Pharmaceutical Supplements"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="310"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <div className="mx-auto grid max-w-5xl items-center gap-6 lg:grid-cols-2 lg:gap-12">
            <img
              alt="Anti-Aging Methods"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="310"
              src="/placeholder.svg"
              width="550"
            />
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h3 className="text-2xl font-bold">Anti-Aging Methods</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Discover our comprehensive library of expert-curated documents on effective anti-aging methods. Learn
                  about the latest scientific breakthroughs and practical strategies to help you look and feel your best
                  at any age.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
