/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ja4z6z8EFTq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Card } from "@/components/ui/card"

export function Component_ja4z6z8EFTq() {
  return (
    <div className="flex flex-col items-center justify-center py-12 md:py-20">
      <div className="flex flex-col items-center space-y-6">
        <Avatar className="h-24 w-24">
          <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
          <AvatarFallback>JD</AvatarFallback>
        </Avatar>
        <div className="text-center">
          <h1 className="text-3xl font-bold">John Doe</h1>
          <p className="text-gray-500 dark:text-gray-400">Health Enthusiast</p>
        </div>
      </div>
      <div className="mt-12 grid w-full max-w-3xl grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        <Card className="flex flex-col items-center justify-center p-6">
          <div className="flex items-center justify-center rounded-full bg-gray-100 p-4 dark:bg-gray-800">
            <AwardIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
          </div>
          <div className="mt-4 text-center">
            <h3 className="text-xl font-bold">Awards</h3>
            <p className="text-gray-500 dark:text-gray-400">12</p>
          </div>
        </Card>
        <Card className="flex flex-col items-center justify-center p-6">
          <div className="flex items-center justify-center rounded-full bg-gray-100 p-4 dark:bg-gray-800">
            <MapIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
          </div>
          <div className="mt-4 text-center">
            <h3 className="text-xl font-bold">Walks</h3>
            <p className="text-gray-500 dark:text-gray-400">150</p>
          </div>
        </Card>
        <Card className="flex flex-col items-center justify-center p-6">
          <div className="flex items-center justify-center rounded-full bg-gray-100 p-4 dark:bg-gray-800">
            <BedIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
          </div>
          <div className="mt-4 text-center">
            <h3 className="text-xl font-bold">Sleep</h3>
            <p className="text-gray-500 dark:text-gray-400">8 hrs</p>
          </div>
        </Card>
        <Card className="flex flex-col items-center justify-center p-6">
          <div className="flex items-center justify-center rounded-full bg-gray-100 p-4 dark:bg-gray-800">
            <NutIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
          </div>
          <div className="mt-4 text-center">
            <h3 className="text-xl font-bold">Nutrition</h3>
            <p className="text-gray-500 dark:text-gray-400">85%</p>
          </div>
        </Card>
        <Card className="col-span-1 md:col-span-2 lg:col-span-1 flex flex-col items-center justify-center p-6">
          <div className="flex items-center justify-center rounded-full bg-gray-100 p-4 dark:bg-gray-800">
            <GoalIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
          </div>
          <div className="mt-4 text-center">
            <h3 className="text-xl font-bold">Health Score</h3>
            <p className="text-gray-500 dark:text-gray-400">92</p>
          </div>
        </Card>
      </div>
    </div>
  )
}

function AwardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="8" r="6" />
      <path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11" />
    </svg>
  )
}


function BedIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 4v16" />
      <path d="M2 8h18a2 2 0 0 1 2 2v10" />
      <path d="M2 17h20" />
      <path d="M6 8v9" />
    </svg>
  )
}


function GoalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 13V2l8 4-8 4" />
      <path d="M20.561 10.222a9 9 0 1 1-12.55-5.29" />
      <path d="M8.002 9.997a5 5 0 1 0 8.9 2.02" />
    </svg>
  )
}


function MapIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z" />
      <path d="M15 5.764v15" />
      <path d="M9 3.236v15" />
    </svg>
  )
}


function NutIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 4V2" />
      <path d="M5 10v4a7.004 7.004 0 0 0 5.277 6.787c.412.104.802.292 1.102.592L12 22l.621-.621c.3-.3.69-.488 1.102-.592A7.003 7.003 0 0 0 19 14v-4" />
      <path d="M12 4C8 4 4.5 6 4 8c-.243.97-.919 1.952-2 3 1.31-.082 1.972-.29 3-1 .54.92.982 1.356 2 2 1.452-.647 1.954-1.098 2.5-2 .595.995 1.151 1.427 2.5 2 1.31-.621 1.862-1.058 2.5-2 .629.977 1.162 1.423 2.5 2 1.209-.548 1.68-.967 2-2 1.032.916 1.683 1.157 3 1-1.297-1.036-1.758-2.03-2-3-.5-2-4-4-8-4Z" />
    </svg>
  )
}
